# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  zoho_authtoken: <%= ENV["ZOHO_AUTHTOKEN"] %>
  zoho_organization_id: <%= ENV["ZOHO_ORGANIZATION_ID"] %>
  zoho_tax_id: <%= ENV["ZOHO_TAX_ID"] %>

development:
  <<: *common
  secret_key_base: 05621e6990a46966c8648f86975a3bf0131c04f210cdc37efe9b2e3940685b0549f71b9f1575bb24a45b838f5def772cdcf5cf88c1da764e20a3893fd0bb2fef

test:
  <<: *common
  secret_key_base: f759a794e117147fdc195750105b4320301d6768f6c2cdd8065bb93ff9d7a232f47c3dc7236661c0dde2a3718f24cc52e259145a64a663cc949ac5c5c0f79596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
